stages:
  - test

variables:
  APP_ENV: testing
  APP_DEBUG: "true"
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite
  COMPOSER_ALLOW_SUPERUSER: "1"

test:
  stage: test
  image: php:8.2

  before_script:
    - apt-get update && apt-get install -y git unzip curl nodejs npm libzip-dev libpng-dev libicu-dev libonig-dev libxml2-dev libsqlite3-dev sqlite3
    - docker-php-ext-install pdo pdo_sqlite mbstring bcmath intl zip
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - cp .env.example .env
    - mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache database
    - touch database/database.sqlite
    - chmod -R 777 storage bootstrap/cache database
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - npm ci
    - npm run build
    - php artisan key:generate
    - echo "APP_ENV=testing" >> .env
    - echo "APP_DEBUG=true" >> .env
    - echo "DB_CONNECTION=sqlite" >> .env
    - echo "DB_DATABASE=database/database.sqlite" >> .env
    - php artisan migrate --force
    - php artisan optimize:clear

  script:
    - php artisan test